set(_SKY_PLUGINS_SWITCHES_CONFIG "${ENGINE_ROOT}/plugins/plugins.json")

if (NOT EXISTS "${_SKY_PLUGINS_SWITCHES_CONFIG}")
    message(FATAL_ERROR "plugins/plugins.json not found: ${_SKY_PLUGINS_SWITCHES_CONFIG}")
endif()

file(READ "${_SKY_PLUGINS_SWITCHES_CONFIG}" _SKY_PLUGINS_SWITCHES_JSON)
string(MD5 _SKY_PLUGINS_SWITCHES_HASH "${_SKY_PLUGINS_SWITCHES_JSON}")

set(_SKY_PLUGINS_SWITCHES_HASH_PREV "" CACHE INTERNAL
    "MD5 of plugins/plugins.json on last configure")

if (NOT "${_SKY_PLUGINS_SWITCHES_HASH}" STREQUAL "${_SKY_PLUGINS_SWITCHES_HASH_PREV}")
    message(STATUS "[SkyEngine] plugins/plugins.json changed - refreshing plugin switches")
    set(_SKY_PLUGINS_SWITCHES_HASH_PREV "${_SKY_PLUGINS_SWITCHES_HASH}"
        CACHE INTERNAL "MD5 of plugins/plugins.json on last configure" FORCE)
    set(_SKY_PLUGIN_SWITCHES_CHANGED TRUE)
else()
    set(_SKY_PLUGIN_SWITCHES_CHANGED FALSE)
endif()

string(JSON _sky_plugin_count LENGTH "${_SKY_PLUGINS_SWITCHES_JSON}" "plugins")
if (_sky_plugin_count GREATER 0)
    math(EXPR _sky_plugin_last "${_sky_plugin_count} - 1")
    foreach(_i RANGE ${_sky_plugin_last})
        string(JSON _plugin_name GET "${_SKY_PLUGINS_SWITCHES_JSON}" "plugins" "${_i}" "name")
        string(JSON _cmake_var   GET "${_SKY_PLUGINS_SWITCHES_JSON}" "plugins" "${_i}" "cmake_var")
        string(JSON _enabled     GET "${_SKY_PLUGINS_SWITCHES_JSON}" "plugins" "${_i}" "enabled")
        if (_enabled)
            set(_default ON)
        else()
            set(_default OFF)
        endif()
        if (_SKY_PLUGIN_SWITCHES_CHANGED)
            set(${_cmake_var} ${_default} CACHE BOOL "Plugin switch: ${_plugin_name}" FORCE)
        else()
            set(${_cmake_var} ${_default} CACHE BOOL "Plugin switch: ${_plugin_name}")
        endif()
    endforeach()
endif()

# cpython is derived from python plugin switch.
if (SKY_BUILD_PYTHON)
    set(SKY_BUILD_CPYTHON ON CACHE BOOL "CPython embed (required by python plugin)" FORCE)
else()
    set(SKY_BUILD_CPYTHON OFF CACHE BOOL "CPython embed (required by python plugin)" FORCE)
endif()

unset(_sky_plugin_count)
unset(_sky_plugin_last)
unset(_i)
unset(_plugin_name)
unset(_cmake_var)
unset(_enabled)
unset(_default)
unset(_SKY_PLUGIN_SWITCHES_CHANGED)
unset(_SKY_PLUGINS_SWITCHES_JSON)
unset(_SKY_PLUGINS_SWITCHES_HASH)
unset(_SKY_PLUGINS_SWITCHES_CONFIG)
